# Optional display profile marker for MediaServer images.
#
# Raspberry Pi display and firmware settings are generated by the separate
# rpi-config recipe.  In this BSP they are not image variables: assigning
# HDMI_* or RPI_EXTRA_CONFIG in an image recipe does not alter rpi-config's
# datastore.  Keep those settings in build/conf/local.conf or a machine
# configuration, where they are effective for rpi-config.
#
# The class is nevertheless deliberately available as an explicit opt-in so
# image selection documents that the deployment expects the display profile.
# It does not install Qt, a compositor, or touchscreen support.
MEDIASERVER_DISPLAY_PROFILE = "hdmi"

# A touchscreen overlay is a Device Tree/machine concern, not HDMI.  If the
# product uses the existing ADS7846 panel, configure it with KERNEL_DEVICETREE
# and RPI_EXTRA_CONFIG in the selected machine/build configuration.
